import { StaticPageLayout } from "@/components/StaticPageLayout";

export default function TermsOfServicePage() {
    return (
        <StaticPageLayout
            title="Terms of Service"
            subtitle="Please read these terms carefully before using CareerSpire."
            lastUpdated="April 18, 2026"
        >
            <section>
                <h2>1. Acceptance of Terms</h2>
                <p>
                    By creating an account or using CareerSpire, you agree to these Terms of Service. If you do not agree, do not use the platform. These terms apply to all users including free-tier, paid subscribers, and visitors.
                </p>
            </section>

            <section>
                <h2>2. What CareerSpire Provides</h2>
                <p>
                    CareerSpire is an AI-powered interview preparation platform that offers:
                </p>
                <ul>
                    <li>AI mock interviews (text-based and video) with automated scoring and feedback.</li>
                    <li>A Practice Hub with DSA coding problems, an in-browser code editor, and test runner.</li>
                    <li>AI Tutor chat for on-demand learning assistance across programming topics.</li>
                    <li>Curated and AI-generated learning tracks for interview preparation.</li>
                    <li>A community space for sharing interview experiences and video recordings.</li>
                    <li>Gamification features including XP, coins, streaks, badges, and leaderboards.</li>
                </ul>
            </section>

            <section>
                <h2>3. User Accounts</h2>
                <p>
                    You must provide a valid email address and create a password (at least 6 characters) to register. You are responsible for maintaining the confidentiality of your credentials. You must not share your account or let others access the platform through your login.
                </p>
                <p>
                    We reserve the right to suspend or terminate accounts that violate these terms, engage in abusive behaviour, or attempt to exploit the platform.
                </p>
            </section>

            <section>
                <h2>4. Subscriptions &amp; Payments</h2>
                <p>
                    CareerSpire offers a free tier and paid plans (Pro at &#8377;499/month, Placement at &#8377;999/month). All payments are processed in Indian Rupees (INR) through <strong>Razorpay</strong>. Paid subscriptions auto-renew at the end of each billing cycle unless cancelled.
                </p>
                <p>
                    Pay-as-you-go mock packs and voice interview packs are one-time purchases and do not auto-renew. Pricing is subject to change with 30 days&apos; notice.
                </p>
            </section>

            <section>
                <h2>5. Acceptable Use</h2>
                <p>You agree not to:</p>
                <ul>
                    <li>Submit malicious code designed to compromise our servers, other users, or external services through the code editor.</li>
                    <li>Attempt to reverse-engineer, scrape, or bulk-download questions, AI-generated content, or user data.</li>
                    <li>Share offensive, discriminatory, or illegal content in community posts, video interviews, or comments.</li>
                    <li>Create multiple accounts to exploit free-tier limits or referral systems.</li>
                    <li>Use automated bots or scripts to interact with the platform.</li>
                </ul>
            </section>

            <section>
                <h2>6. Code Execution</h2>
                <p>
                    CareerSpire runs user-submitted code (JavaScript, Python, Java) in a restricted server-side environment for the purpose of evaluating solutions against test cases. Code execution is subject to a 3-second time limit and 256MB memory cap. We reserve the right to reject or terminate execution of code that appears malicious.
                </p>
            </section>

            <section>
                <h2>7. AI-Generated Content</h2>
                <p>
                    Interview questions, feedback, tutor responses, and learning guides are generated by AI (Groq and Google Gemini). While we strive for accuracy, AI outputs may occasionally contain errors. CareerSpire is a preparation tool, not a guarantee of interview success. You should verify technical advice independently.
                </p>
            </section>

            <section>
                <h2>8. Your Content</h2>
                <p>
                    You retain ownership of code you write, answers you submit, and interview experiences you share. By making content public (e.g. video interviews, community experiences), you grant CareerSpire a non-exclusive licence to display that content on the platform. You can revoke this by making the content private or deleting it.
                </p>
            </section>

            <section>
                <h2>9. Intellectual Property</h2>
                <p>
                    The CareerSpire platform, its design, brand, logo (the CS monogram), AI question bank, and curated learning tracks are the intellectual property of CareerSpire. You may not copy, redistribute, or commercially use any part of the platform without written permission.
                </p>
            </section>

            <section>
                <h2>10. Limitation of Liability</h2>
                <p>
                    CareerSpire is provided &quot;as is&quot; without warranty of any kind. We are not liable for interview outcomes, hiring decisions, data loss due to force majeure, or AI-generated content inaccuracies. Our total liability is limited to the amount you have paid us in the 12 months preceding a claim.
                </p>
            </section>

            <section>
                <h2>11. Account Termination</h2>
                <p>
                    You may delete your account at any time from Settings or by emailing us. We may terminate or suspend your access for violations of these terms. Upon termination, your data is handled as described in our Privacy Policy.
                </p>
            </section>

            <section>
                <h2>12. Governing Law</h2>
                <p>
                    These terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in New Delhi, India.
                </p>
            </section>

            <section>
                <h2>13. Changes to These Terms</h2>
                <p>
                    We may update these terms with at least 30 days&apos; notice via email or in-app notification. Continued use after the effective date constitutes acceptance. If you disagree with changes, you may cancel your subscription and delete your account before they take effect.
                </p>
            </section>

            <section>
                <h2>14. Contact</h2>
                <p>
                    Questions about these terms? Email us at <a href="mailto:support@careerspire.com">support@careerspire.com</a>.
                </p>
            </section>
        </StaticPageLayout>
    );
}
