import { StaticPageLayout } from "@/components/StaticPageLayout";

export default function LicensePage() {
    return (
        <StaticPageLayout
            title="License Agreement"
            subtitle="The terms governing your use of the CareerSpire platform and its content."
            lastUpdated="April 18, 2026"
        >
            <section>
                <h2>1. Grant of Licence</h2>
                <p>
                    CareerSpire grants you a personal, non-exclusive, non-transferable, revocable licence to access and use the platform for your own interview preparation. This licence covers the web application, AI-generated content, curated learning tracks, and the Practice Hub tools.
                </p>
            </section>

            <section>
                <h2>2. Your Content</h2>
                <p>
                    You retain full ownership of code you write, answers you provide, and interview experiences you share on CareerSpire. By submitting code to the Practice Hub or a mock interview, you grant us a limited licence to execute it server-side for the purpose of running test cases and generating feedback. We do not claim ownership of your submissions.
                </p>
            </section>

            <section>
                <h2>3. AI-Generated Content</h2>
                <p>
                    Interview questions, feedback reports, tutor responses, topic guides, and learning track syllabi generated by our AI (powered by Groq and Google Gemini) are provided for your personal use. You may reference AI feedback in your own notes or preparation materials. You may not bulk-export, republish, or commercially redistribute AI-generated content from CareerSpire.
                </p>
            </section>

            <section>
                <h2>4. Restrictions</h2>
                <p>Under this licence, you may not:</p>
                <ul>
                    <li>Scrape, crawl, or bulk-download questions, answers, or AI outputs from the platform.</li>
                    <li>Reverse-engineer the question generation, code evaluation, or feedback scoring systems.</li>
                    <li>Resell, sublicence, or redistribute access to CareerSpire or its content.</li>
                    <li>Remove or alter any copyright notices, branding, or attribution.</li>
                    <li>Use CareerSpire&apos;s content to train competing AI models or build derivative products.</li>
                </ul>
            </section>

            <section>
                <h2>5. CareerSpire&apos;s Intellectual Property</h2>
                <p>
                    The CareerSpire brand, the CS monogram logo, the curated question bank, the platform&apos;s design and UI, and all proprietary algorithms (question caching, adaptive difficulty, gamification logic) are the exclusive property of CareerSpire. The open-source libraries we use retain their respective licences.
                </p>
            </section>

            <section>
                <h2>6. Community Content</h2>
                <p>
                    Interview experiences, video recordings made public, and comments posted in the community section are visible to all users. By publishing community content, you grant CareerSpire a non-exclusive licence to display it on the platform. You can unpublish or delete your content at any time, which revokes this licence.
                </p>
            </section>

            <section>
                <h2>7. Termination</h2>
                <p>
                    This licence remains in effect as long as your account is active. It terminates immediately if you violate these terms or our Terms of Service. Upon termination, you must stop using the platform. Sections 4 (Restrictions) and 5 (Intellectual Property) survive termination.
                </p>
            </section>

            <section>
                <h2>8. Contact</h2>
                <p>
                    For licensing questions or commercial use enquiries, email <a href="mailto:support@careerspire.com">support@careerspire.com</a>.
                </p>
            </section>
        </StaticPageLayout>
    );
}
